compilationUnit ::= (directive | directive*)?;

directive ::= TEXT? ( importDirective | renderDirective ) TEXT?

importDirective ::= '@import' '(' STRING ')'
                 | '@import' '(' STRING ',' STRING ')';


renderDirective ::= '@render' '(' kiwiElement ')';

kiwiElement ::= selfClosingElement
        | startTag
            childrenElements
          endTag;

startTag ::= '<' IDENTIFIER attributes? '>';

endTag ::= '</' IDENTIFIER '>';

selfClosingElement ::= '<' IDENTIFIER attributes? '/>';

childrenElements ::= (kiwiElement | kiwiElement*)?;

attributes ::= (attribute | attribute*);

attribute ::= IDENTIFIER | IDENTIFIER '=' STRING;
