package org.github.jmorla.kiwicompiler;

import org.github.jmorla.kiwicompiler.ast.Attribute;
import org.github.jmorla.kiwicompiler.ast.Segment;
import org.github.jmorla.kiwicompiler.ast.SyntaxTree;
import org.github.jmorla.kiwicompiler.visitor.SegmentVisitor;

import java.io.*;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public final class KiwiGenerator {

    private final Configuration config;

    private KiwiGenerator(Configuration config) {
        this.config = config;
    }

    public static class Configuration {}

    public static KiwiGenerator withDefault() {
        return new KiwiGenerator(new Configuration());
    }


    public void generate(Reader source, Writer tOut, Writer jsOut) {
        var tokens = new KiwiScanner(source).scanTokens();
        var syntaxTree = new KiwiParser(tokens).parse();
        compileHtml(syntaxTree, tOut);
        compileJs(syntaxTree, jsOut);
    }

    public String generateJs(String source) {
        var writer = new StringWriter();
        generateJs(new StringReader(source), writer);
        return writer.toString();
    }

    public void generateJs(Reader source, Writer out) {
        var tokens = new KiwiScanner(source).scanTokens();
        var syntaxTree = new KiwiParser(tokens).parse();
        compileJs(syntaxTree, out);
    }

    public String generateHtml(String source) {
        var writer = new StringWriter();
        generateHtml(new StringReader(source), writer);
        return writer.toString();
    }

    public void generateHtml(Reader source, Writer out) {
        var tokens = new KiwiScanner(source).scanTokens();
        var syntaxTree = new KiwiParser(tokens).parse();
        compileHtml(syntaxTree, out);
    }

    private void compileJs(SyntaxTree tree, Writer jsOut) {
        tree.accept(new JsGenerator(jsOut));
    }

    private void compileHtml(SyntaxTree tree, Writer htmlOut) {
        tree.accept(new HtmlGenerator(htmlOut));
    }

    private static class JsGenerator implements SegmentVisitor, AutoCloseable {
        private final PrintWriter out;
        private final Set<String> ids = new HashSet<>();

        public JsGenerator(Writer writer) {
            out = new PrintWriter(writer);
            printGeneratedNote();
            printReactImports();
        }

        @Override
        public void visit(Segment.TextSegment n) {
        }

        @Override
        public void visit(Segment.ImportDirective n) {
            out.print("import ");
            out.print(n.arg0());
            out.print(" from '");
            out.print(n.hasSingleArg() ? "./" : n.arg1());
            out.println("';");
        }

        @Override
        public void visit(Segment.RenderDirective n) {
            var element = n.element();
            var baseIdentifier = (element.identifier() + Math.abs(element.hashCode()));
            if (ids.contains(baseIdentifier)) {
                return;
            }
            ids.add(baseIdentifier);
            var elementsVarName = baseIdentifier.toLowerCase() + "_elements";
            out.print("\n");
            out.print("const ");
            out.print(elementsVarName);
            out.print(" = ");
            out.print("document.querySelectorAll('[data-kiwi-id=\"");
            out.print(baseIdentifier);
            out.println("\"]');");

            out.print("for(let element of ");
            out.print(elementsVarName);
            out.println(") {");
            if (element.hasAttributes()) {
                printProps(element.attributes());
            }
            out.println("\tconst root = createRoot(element);");
            out.print("\troot.render(");
            out.print("<");
            out.print(element.identifier());
            if (element.hasAttributes()) {
                out.print(" {...props} ");
            }
            out.println("/>);");
            out.println("}");
        }

        private void printProps(List<Attribute> attributes) {
            out.println("\tconst props = {");
            for (var attribute : attributes) {
                out.print("\t\t");
                out.print(attribute.identifier());
                out.print(": ");
                if (attribute.type().equals(Attribute.AttributeType.BOOLEAN)) {
                    out.print("'true' == ");
                }
                if (attribute.type().equals(Attribute.AttributeType.NUMERIC)) {
                    out.print("Number");
                }
                out.print("(element.getAttribute('data-prop-");
                out.print(attribute.identifier());
                out.println("')),");
            }
            out.println("\t};");
        }

        private void printGeneratedNote() {
            out.print("""
                    /*
                        This source is generated by Kiwi-compiler
                        do not modify this code
                    */
                    """);
        }

        private void printReactImports() {
            out.println("import React from 'react';");
            out.println("import { createRoot } from 'react-dom/client';");
        }

        @Override
        public void close() {
            out.close();
        }
    }

    private static class HtmlGenerator implements SegmentVisitor, AutoCloseable {
        private final PrintWriter out;

        public HtmlGenerator(Writer writer) {
            out = new PrintWriter(writer);
        }

        @Override
        public void visit(Segment.TextSegment n) {
            if (n.text().isBlank()) {
                return;
            }
            out.println(n.text());
        }

        @Override
        public void visit(Segment.ImportDirective n) {
        }

        @Override
        public void visit(Segment.RenderDirective n) {
            var element = n.element();
            out.print("<div data-kiwi-id=\"");
            out.print(element.identifier());
            out.print(Math.abs(element.hashCode()));
            out.print('"');
            if (element.hasAttributes()) {
                for (var attributes : element.attributes()) {
                    out.print(" data-prop-");
                    out.print(attributes.identifier());
                    out.print("=");
                    out.print('"');
                    out.print(attributes.value());
                    out.print('"');
                }
            }
            out.print("></div>\n");
        }

        @Override
        public void close() {
            out.close();
        }
    }
}
